Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/bionic64"

  # Configuração da guest machine
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "private_network", ip: "10.80.4.10"

    mysqlserver.vm.provider "virtualbox" do |vb|
      vb.name = "Atividade_1_mysqlserver"
    end

    mysqlserver.vm.provision "shell", inline: $mysql_shell_install
  end

  $mysql_shell_install = <<-SCRIPT
    apt update && \
    apt install -y mysql-server && \
    cat /vagrant/mysql/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf && \
    service mysql restart && \
    type mysql && \
    echo "MySQL Instalado" && \
    `mysql -u root -e "\
    CREATE USER 'vagrant'@10.80.4.1 IDENTIFIED BY 'vagrant'; \
    GRANT ALL PRIVILEGES ON * . * TO 'vagrant'@10.80.4.1; \
    FLUSH PRIVILEGES;"`
    exit;
  SCRIPT
end
