apiVersion: v1
kind: Service
metadata:
    name: mysql-s
spec:
    type: ClusterIP
    selector:
        app: mysql-app
    ports:
      - name: "3306"
        port: 3306
        protocol: TCP
        targetPort: 3306