apiVersion: v1
kind: Service
metadata:
    name: nginx-s
spec:
    type: LoadBalancer
    selector:
        app: nginx-app
    ports:
      - name: "80"
        port: 80
        protocol: TCP
        targetPort: 80